from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
print("Las clases")
clases=le.fit([1, 2, 2, 6])
print(clases.classes_)
Y=[1, 1, 2, 6]
print("Objeto que clasificaremos")
print(Y)
clasifica=le.transform(Y)
print("Clasifica de acuerdo a nuestras clases")
print(clasifica)
invertir=le.inverse_transform([0, 0, 1, 2])
print("Podemos invertir")
print(invertir)
le = LabelEncoder()
clases=le.fit(["paris", "paris", "tokyo", "amsterdam"])
print("Las clases")
print(clases.classes_)
Y2=["tokyo", "tokyo", "paris"]
print("Objeto que clasificaremos: ",Y2)
clasificar=le.transform(Y2)
print("Clasificacion")
print(clasificar)
print("Podemos invertir ",[2,2,1])
invertir=le.inverse_transform([2, 2, 1])
print(invertir)
